const fs = require("fs");
require("dotenv").config();

const config = {
  SESSION_ID: process.env.SESSION_ID || "",
  DB_TYPE: process.env.DB_TYPE || 'sqlite',
  DATABASE_URL: process.env.DATABASE_URL || '',
  DATABASE_URL_PUBLIC: process.env.DATABASE_URL_PUBLIC || '',
  MONGODB_URI: process.env.MONGODB_URI || '',
  MONGO_DB_NAME: process.env.MONGO_DB_NAME || 'djousse_tech',
  PREFIX: process.env.PREFIX || '.',
  BOT_NAME: process.env.BOT_NAME || "DJOUSSE-TECH-MD",
  BOT: process.env.BOT || "hello 👋",
  NEW_CMD: process.env.NEW_CMD || "addvar\n| sudo\n| djousse",
  CAPTION: process.env.CAPTION || "ᴘᴏᴡᴇʀᴇᴅ ʙʏ DJOUSSE TECH",
  AUTO_STATUS_SEEN: process.env.AUTO_STATUS_SEEN !== undefined ? process.env.AUTO_STATUS_SEEN === 'true' : true,
  AUTO_BIO: process.env.AUTO_BIO !== undefined ? process.env.AUTO_BIO === 'true' : true,
  AUTO_STATUS_REACT: process.env.AUTO_STATUS_REACT !== undefined ? process.env.AUTO_STATUS_REACT === 'true' : true,
  ANTI_LEFT: process.env.ANTI_LEFT !== undefined ? process.env.ANTI_LEFT === 'true' : true,
  AUTOLIKE_EMOJI: process.env.AUTOLIKE_EMOJI || '💚',
  AUTO_REPLY_STATUS: process.env.AUTO_REPLY_STATUS !== undefined ? process.env.AUTO_REPLY_STATUS === 'true' : false,
  STATUS_READ_MSG: process.env.STATUS_READ_MSG || 'Status Viewed by DJOUSSE-TECH-MD',
  VOICE_CHAT_BOT: process.env.VOICE_CHAT_BOT !== undefined ? process.env.VOICE_CHAT_BOT === 'true' : false,
  ANTILINK: process.env.ANTILINK !== undefined ? process.env.ANTILINK === 'true' : false,
  AUTO_STICKER: process.env.AUTO_STICKER !== undefined ? process.env.AUTO_STICKER === 'true' : false,
  AUTO_READ: process.env.AUTO_READ !== undefined ? process.env.AUTO_READ === 'true' : false,
  AUTO_TYPING: process.env.AUTO_TYPING !== undefined ? process.env.AUTO_TYPING === 'true' : false,
  AUTO_RECORDING: process.env.AUTO_RECORDING !== undefined ? process.env.AUTO_RECORDING === 'true' : false,
  ALWAYS_ONLINE: process.env.ALWAYS_ONLINE !== undefined ? process.env.ALWAYS_ONLINE === 'true' : false,
  AUTO_REACT: process.env.AUTO_REACT !== undefined ? process.env.AUTO_REACT === 'true' : false,
  AUTO_BLOCK: process.env.AUTO_BLOCK !== undefined ? process.env.AUTO_BLOCK === 'true' : true,
  ANTI_DELETE: process.env.ANTI_DELETE !== undefined ? process.env.ANTI_DELETE === 'true' : false,
  CHAT_BOT: process.env.CHAT_BOT !== undefined ? process.env.CHAT_BOT === 'true' : false,
  CHAT_BOT_MODE: process.env.CHAT_BOT_MODE || "public",
  LYDEA: process.env.LYDEA !== undefined ? process.env.LYDEA === 'true' : false,
  REJECT_CALL: process.env.REJECT_CALL !== undefined ? process.env.REJECT_CALL === 'true' : false,
  NOT_ALLOW: process.env.NOT_ALLOW !== undefined ? process.env.NOT_ALLOW === 'true' : true,
  MODE: process.env.MODE || "public",
  DELETED_MESSAGES_CHAT_ID: process.env.DELETED_MESSAGES_CHAT_ID || "",
  OWNER_NAME: process.env.OWNER_NAME || "DJOUSSSE",
  OWNER_NUMBER: process.env.OWNER_NUMBER || "237693978044",
  SUDO_NUMBER: process.env.SUDO_NUMBER || "237693978044",
  GEMINI_KEY: process.env.GEMINI_API_KEY || process.env.GEMINI_KEY || '',
  WELCOME: process.env.WELCOME !== undefined ? process.env.WELCOME === 'true' : false,

  ANTI_DEL_PATH: process.env.ANTI_DEL_PATH || 'inbox',
  ADMIN_EVENTS: process.env.ADMIN_EVENTS !== undefined ? process.env.ADMIN_EVENTS === 'true' : false,
  MENTION_REPLY: process.env.MENTION_REPLY !== undefined ? process.env.MENTION_REPLY === 'true' : false,
  MENU_IMAGE_URL: process.env.MENU_IMAGE_URL || 'media/djousse.jpg',
  STICKER_NAME: process.env.STICKER_NAME || 'DJOUSSE-TECH-MD',
  CUSTOM_REACT: process.env.CUSTOM_REACT !== undefined ? process.env.CUSTOM_REACT === 'true' : false,
  CUSTOM_REACT_EMOJIS: process.env.CUSTOM_REACT_EMOJIS || '💝,💖,💗,❤️‍🩹,❤️,🧡,💛,💚,💙,💜,🤎,🖤,🤍',
  DELETE_LINKS: process.env.DELETE_LINKS !== undefined ? process.env.DELETE_LINKS === 'true' : false,
  ALIVE_VID: process.env.ALIVE_VID || 'https://files.catbox.moe/2myos8.mp4',
  ANTI_BAD: process.env.ANTI_BAD !== undefined ? process.env.ANTI_BAD === 'true' : false,
  ANTI_LINK_KICK: process.env.ANTI_LINK_KICK !== undefined ? process.env.ANTI_LINK_KICK === 'true' : false,
  AUTO_REPLY: process.env.AUTO_REPLY !== undefined ? process.env.AUTO_REPLY === 'true' : false,
  PUBLIC_MODE: process.env.PUBLIC_MODE !== undefined ? process.env.PUBLIC_MODE === 'true' : true,
  READ_CMD: process.env.READ_CMD !== undefined ? process.env.READ_CMD === 'true' : false,
  ANTI_VV: process.env.ANTI_VV !== undefined ? process.env.ANTI_VV === 'true' : false,
  ANTIBOT: process.env.ANTIBOT !== undefined ? process.env.ANTIBOT === 'true' : false,
  ANTIBOT_WARNINGS: parseInt(process.env.ANTIBOT_WARNINGS) || 3
};

module.exports = config;
